"""Add external_id name changes

Revision ID: 37667120c20a
Revises: a62cad333e8e
Create Date: 2024-11-25 14:28:56.287919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37667120c20a'
down_revision = 'a62cad333e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('uq_event_external_id', type_='unique')
        batch_op.create_foreign_key('fk_event_customer', 'customers', ['customer_id'], ['id'])  # Added constraint name
        batch_op.drop_column('external_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_external_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('uq_transaction_external_id', type_='unique')
        batch_op.create_unique_constraint('uq_transaction_sale_external_id', ['sale_external_id'])  # Added constraint name
        batch_op.create_foreign_key('fk_transaction_customer', 'customers', ['customer_id'], ['id'])  # Added constraint name
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('fk_transaction_customer', type_='foreignkey')
        batch_op.drop_constraint('uq_transaction_sale_external_id', type_='unique')
        batch_op.create_unique_constraint('uq_transaction_external_id', ['external_id'])
        batch_op.drop_column('customer_id')
        batch_op.drop_column('sale_external_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('fk_event_customer', type_='foreignkey')
        batch_op.create_unique_constraint('uq_event_external_id', ['external_id'])
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
