"""Add external_id to transactions and events table

Revision ID: a62cad333e8e
Revises: c3c70c48321a
Create Date: 2024-11-25 14:01:55.184783
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62cad333e8e'
down_revision = 'c3c70c48321a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        # Add the new external_id column
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=False))
        # Make it unique
        batch_op.create_unique_constraint('uq_event_external_id', ['external_id'])
        
        # Drop the foreign key and customer_id column
        batch_op.drop_constraint('fk_event_customer', type_='foreignkey')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        # Add the new external_id column
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=False))
        # Make it unique
        batch_op.create_unique_constraint('uq_transaction_external_id', ['external_id'])
        
        # Drop the foreign key and customer_id column
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        # Re-add the customer_id column and foreign key constraint
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_transaction_customer', 'customers', ['customer_id'], ['id'])
        
        # Drop the unique constraint on external_id
        batch_op.drop_constraint('uq_transaction_external_id', type_='unique')
        batch_op.drop_column('external_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        # Re-add the customer_id column and foreign key constraint
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_event_customer', 'customers', ['customer_id'], ['id'])
        
        # Drop the unique constraint on external_id
        batch_op.drop_constraint('uq_event_external_id', type_='unique')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###

